# Generated by Django 4.0.8 on 2022-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
