# Generated by Django 4.0.8 on 2022-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersSystem', '0003_alter_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(max_length=500, null=True, upload_to=None),
        ),
    ]
