# Generated by Django 4.0.8 on 2022-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersSystem', '0004_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductPrice',
            field=models.BigIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(max_length=500, null=True, upload_to='media'),
        ),
    ]
